### ISSUE TITLE
Demo page broken on Safari

### ISSUE THREAD

**Issue by mundizzle** [nxtexe/react-motion-router#2]
Hi there! Cool library. I noticed the demo page is showing blank on Safari. Works fine for me on Chrome.

<img width="861" alt="CleanShot 2022-02-24 at 11 34 26@2x" src="https://user-images.githubusercontent.com/1226055/155594677-5aedda7b-a370-44a2-8e74-37862491e7f2.png">

<img width="396" alt="CleanShot 2022-02-24 at 11 36 03@2x" src="https://user-images.githubusercontent.com/1226055/155594773-65582035-6e55-4711-b512-305bac6ff7f1.png">

**Comment by absurdprofit** [comment]
Thanks for the heads up. Seems like TouchEvent isn't supported on Safari. [Reference](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/TouchEvent). Since Mac devices don't even have touch screens I'm just going to remove gesture events on Mac entirely. This should fix the bug. As I don't have a Mac device testing will be a bit difficult for me so please sympathise with me :).

**Comment by absurdprofit** [comment]
Tested the solution on a friend's Mac. Issue resolved. Can you confirm?

**Comment by absurdprofit** [comment]
Closing this issue since it seems to have been resolved. Feel free to reopen another issue if this isn't the case.
